#!/bin/bash
### BEGIN INIT INFO
# Provides:          cloud_copasi_daemon
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start cloud-copasi daemon
# Description:       Enable service provided by cloud-coapsi daemon.
### END INIT INFO

#Replace ubuntu user with the username you wish to run the cloud-copasi-daemon as
sudo -u cloudcopasi sh -c "/opt/cloud-copasi-client/cloud-copasi-daemon.py $@"
