# Generated by Django 3.1.5 on 2022-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('lb', 'Load balancing'), ('main', 'Main task'), ('process', 'Results processing'), ('file', 'Creating file with optimal values'), ('other', 'Other'), ('PlFiles', 'Generating PL Files')], max_length=32),
        ),
    ]
