# Generated by Django 3.2.12 on 2022-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ssh_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('lb', 'Load balancing'), ('main', 'Main task'), ('process', 'Results processing'), ('file', 'Creating file with optimal values'), ('other', 'Other'), ('PlFiles', 'Generating PL Files')], max_length=32),
        ),
    ]
