# Generated by Django 3.1.5 on 2021-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20210714_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorpool',
            name='platform',
            field=models.CharField(choices=[('DEB6', 'Debian 6'), ('DEB7', 'Debian 7'), ('RH5', 'Red Hat 5'), ('RH6', 'Red Hat 6'), ('RH7', 'Red Hat 7'), ('CentOS7', 'CentOS 7'), ('UBUNTU12', 'Ubuntu 12'), ('MACOS', 'MAC OS')], default='DEB6', max_length=8, verbose_name='The platform of the remote condor submitter we are connecting to'),
        ),
    ]
