# Generated by Django 3.2.12 on 2022-06-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20220610_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ssh_free',
        ),
    ]
