# Generated by Django 3.1.5 on 2022-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_auto_20220425_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpc',
            name='internet_gateway_id',
            field=models.CharField(max_length=45, verbose_name='Internet gateway ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='master_group_id',
            field=models.CharField(max_length=45, verbose_name='Condor Master security group ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='route_table_association_id',
            field=models.CharField(max_length=45, verbose_name='Route table and subnet association ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='route_table_id',
            field=models.CharField(max_length=45, verbose_name='Route table ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='subnet_id',
            field=models.CharField(max_length=45, verbose_name='Subnet ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='vpc_id',
            field=models.CharField(max_length=45, verbose_name='VPC ID'),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='worker_group_id',
            field=models.CharField(max_length=45, verbose_name='Condor Worker security group ID'),
        ),
    ]
