# Generated by Django 3.1.5 on 2022-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_auto_20220819_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccesskey',
            name='aws_region',
            field=models.CharField(default='us-east-1', help_text='AWS Region where you want to use the access key', max_length=100, verbose_name='AWS Access Key Region'),
        ),
    ]
