# Generated by Django 3.1.5 on 2022-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0004_awsaccesskey_aws_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticip',
            name='allocation_id',
            field=models.CharField(max_length=50, verbose_name='The allocation ID for the IP address'),
        ),
        migrations.AlterField(
            model_name='elasticip',
            name='association_id',
            field=models.CharField(max_length=50, verbose_name='The instance association ID for the address'),
        ),
    ]
