# Generated by Django 3.1.5 on 2022-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0005_auto_20220903_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2pool',
            name='alarm_notify_topic_arn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
