# Generated by Django 3.1.5 on 2022-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0006_auto_20220903_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_type',
            field=models.CharField(choices=[('t1.micro', 't2.micro (1 vCPUs, 0.5GB - Free tier eligible)'), ('t2.micro', 't2.micro (1 vCPUs, 1GB - Free tier eligible)'), ('t2.small', 't2.small (1 vCPUs, 2GB)'), ('t2.medium', 't2.medium (2 vCPUs, 2GB)'), ('t2.large', 't2.large (2 vCPUs, 8GB)'), ('a1.medium', 'a1.medium (1 vCPUs, 2GB)'), ('a1.large', 'a1.large (2 vCPUs, 4GB)'), ('a1.xlarge', 'a1.xlarge (4 vCPUs, 8GB)'), ('a1.2xlarge', 'a1.2xlarge (8 vCPUs, 16GB)'), ('m4.large', 'm4.large (2 vCPUs, 8GB, Moderate Network Performance)'), ('m4.xlarge', 'm4.xlarge (4 vCPUs, 16GB, High Network Performance)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ec2pool',
            name='initial_instance_type',
            field=models.CharField(choices=[('t1.micro', 't2.micro (1 vCPUs, 0.5GB - Free tier eligible)'), ('t2.micro', 't2.micro (1 vCPUs, 1GB - Free tier eligible)'), ('t2.small', 't2.small (1 vCPUs, 2GB)'), ('t2.medium', 't2.medium (2 vCPUs, 2GB)'), ('t2.large', 't2.large (2 vCPUs, 8GB)'), ('a1.medium', 'a1.medium (1 vCPUs, 2GB)'), ('a1.large', 'a1.large (2 vCPUs, 4GB)'), ('a1.xlarge', 'a1.xlarge (4 vCPUs, 8GB)'), ('a1.2xlarge', 'a1.2xlarge (8 vCPUs, 16GB)'), ('m4.large', 'm4.large (2 vCPUs, 8GB, Moderate Network Performance)'), ('m4.xlarge', 'm4.xlarge (4 vCPUs, 16GB, High Network Performance)')], default='t2.micro', help_text='The instance type to launch. The price per hour will vary depending on the instance type. For more information on the different instance types see the <a href="">help page</a>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='spotrequest',
            name='instance_type',
            field=models.CharField(choices=[('t1.micro', 't2.micro (1 vCPUs, 0.5GB - Free tier eligible)'), ('t2.micro', 't2.micro (1 vCPUs, 1GB - Free tier eligible)'), ('t2.small', 't2.small (1 vCPUs, 2GB)'), ('t2.medium', 't2.medium (2 vCPUs, 2GB)'), ('t2.large', 't2.large (2 vCPUs, 8GB)'), ('a1.medium', 'a1.medium (1 vCPUs, 2GB)'), ('a1.large', 'a1.large (2 vCPUs, 4GB)'), ('a1.xlarge', 'a1.xlarge (4 vCPUs, 8GB)'), ('a1.2xlarge', 'a1.2xlarge (8 vCPUs, 16GB)'), ('m4.large', 'm4.large (2 vCPUs, 8GB, Moderate Network Performance)'), ('m4.xlarge', 'm4.xlarge (4 vCPUs, 16GB, High Network Performance)')], max_length=20),
        ),
    ]
