# Generated by Django 3.1.5 on 2022-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0008_auto_20221003_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='instance_role',
            field=models.CharField(choices=[('master', 'Master'), ('worker', 'Worker'), ('submit', 'Submit')], max_length=20),
        ),
    ]
