# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condorpool',
            name='pool_type',
            field=models.CharField(choices=[(b'condor', b'Condor'), (b'pbs', b'PBS'), (b'lsf', b'LSF'), (b'sge', b'Sun Grid Engine'), (b'slurm', b'Slurm Workload Manager')], default=b'condor', max_length=20),
        ),
    ]
