name: Build cloud-copasi Docker Container

on:
  push:
    tags:
    - 'docker_build*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_CLOUD_COPASI_USERNAME }}
          password: ${{ secrets.GHCR_CLOUD_COPASI_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          tags: ghcr.io/copasi/cloud-copasi:0.0.19, ghcr.io/copasi/cloud-copasi:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

